//!!!GENERATED BY "GO-SERVICE" DON'T CHANGE THIS FILE!!!
package executor

import (
	"encoding/json"
	"fmt"
	"github.com/pkg/errors"

	"github.com/akaumov/go-service/exchange"
)

type Executor struct {
	handler HandlerInterface
}

type SessionInterface interface {
	GetUserId() string
	GetSessionId() string
}

func NewExecutor(handler HandlerInterface) *Executor {
	return &Executor{
		handler: handler,
	}
}

func (e *Executor) Execute(session SessionInterface, packedMessage *[]byte) (*[]byte, error) {
	if packedMessage == nil {
		return nil, errors.New("message text is required")
	}

	response := e.execute(session, packedMessage)
	packed, _ := json.Marshal(response)
	return &packed, nil
}

func (e *Executor) execute(session SessionInterface, packedMessage *[]byte) exchange.ResponseMessage {

	var requestMessage exchange.RequestMessage
	err := json.Unmarshal(*packedMessage, &requestMessage)
	if err != nil {
		return exchange.NewErrorResponse("", "WrongRequest", "can't parse message")
	}

	requestId := requestMessage.Id

	switch requestMessage.Method {

	case "getFolders":
		var params GetFoldersParams
		err := json.Unmarshal(requestMessage.Params, &params)
		if err != nil {
			return exchange.NewErrorResponse(requestId, "WrongRequest", fmt.Sprintf("can't parse params: %v", err))
		}

		err = params.Validate()
		if err != nil {
			return exchange.NewErrorResponse(requestId, "WrongRequest", fmt.Sprintf("can't wrong params: %v", err))
		}

		result, err := e.handler.GetFolders(session, params.ParentId)
		if err != nil {
			return exchange.NewErrorResponse(requestId, "ServerError", err.Error())
		}

		return exchange.NewResultResponse(requestId, result)

	case "getChildrenItems":
		var params GetChildrenItemsParams
		err := json.Unmarshal(requestMessage.Params, &params)
		if err != nil {
			return exchange.NewErrorResponse(requestId, "WrongRequest", fmt.Sprintf("can't parse params: %v", err))
		}

		err = params.Validate()
		if err != nil {
			return exchange.NewErrorResponse(requestId, "WrongRequest", fmt.Sprintf("can't wrong params: %v", err))
		}

		result, err := e.handler.GetChildrenItems(session, params.FolderId)
		if err != nil {
			return exchange.NewErrorResponse(requestId, "ServerError", err.Error())
		}

		return exchange.NewResultResponse(requestId, result)

	case "sync":
		var params SyncParams
		err := json.Unmarshal(requestMessage.Params, &params)
		if err != nil {
			return exchange.NewErrorResponse(requestId, "WrongRequest", fmt.Sprintf("can't parse params: %v", err))
		}

		err = params.Validate()
		if err != nil {
			return exchange.NewErrorResponse(requestId, "WrongRequest", fmt.Sprintf("can't wrong params: %v", err))
		}

		result, err := e.handler.Sync(session, &params.Operations)
		if err != nil {
			return exchange.NewErrorResponse(requestId, "ServerError", err.Error())
		}

		return exchange.NewResultResponse(requestId, result)

	case "getTask":
		var params GetTaskParams
		err := json.Unmarshal(requestMessage.Params, &params)
		if err != nil {
			return exchange.NewErrorResponse(requestId, "WrongRequest", fmt.Sprintf("can't parse params: %v", err))
		}

		err = params.Validate()
		if err != nil {
			return exchange.NewErrorResponse(requestId, "WrongRequest", fmt.Sprintf("can't wrong params: %v", err))
		}

		result, err := e.handler.GetTask(session, params.Id)
		if err != nil {
			return exchange.NewErrorResponse(requestId, "ServerError", err.Error())
		}

		return exchange.NewResultResponse(requestId, result)

	case "getTasks":
		var params GetTasksParams
		err := json.Unmarshal(requestMessage.Params, &params)
		if err != nil {
			return exchange.NewErrorResponse(requestId, "WrongRequest", fmt.Sprintf("can't parse params: %v", err))
		}

		err = params.Validate()
		if err != nil {
			return exchange.NewErrorResponse(requestId, "WrongRequest", fmt.Sprintf("can't wrong params: %v", err))
		}

		result, err := e.handler.GetTasks(session, params.FolderId)
		if err != nil {
			return exchange.NewErrorResponse(requestId, "ServerError", err.Error())
		}

		return exchange.NewResultResponse(requestId, result)

	case "getFolder":
		var params GetFolderParams
		err := json.Unmarshal(requestMessage.Params, &params)
		if err != nil {
			return exchange.NewErrorResponse(requestId, "WrongRequest", fmt.Sprintf("can't parse params: %v", err))
		}

		err = params.Validate()
		if err != nil {
			return exchange.NewErrorResponse(requestId, "WrongRequest", fmt.Sprintf("can't wrong params: %v", err))
		}

		result, err := e.handler.GetFolder(session, params.FolderId)
		if err != nil {
			return exchange.NewErrorResponse(requestId, "ServerError", err.Error())
		}

		return exchange.NewResultResponse(requestId, result)

	}

	return exchange.NewErrorResponse("", "WrongRequest", "no such method")
}
