//!!!GENERATED BY "GO-SERVICE" DON'T CHANGE THIS FILE!!!
package executor

type HandlerInterface interface {
	GetTask(session SessionInterface, id string) (*Task, error)
	GetTasks(session SessionInterface, folderId *string) (*[]Task, error)
	GetFolder(session SessionInterface, folderId *string) (*Folder, error)
	GetFolders(session SessionInterface, parentId *string) (*[]Folder, error)
	GetChildrenItems(session SessionInterface, folderId *string) (*GetChildrenItemsResult, error)
	Sync(session SessionInterface, operations *[]OperationItem) (*SyncResult, error)
}
