//!!!GENERATED BY "GO-SERVICE" DON'T CHANGE THIS FILE!!!
package executor

type HandlerInterface interface {
	GetAuthor(session SessionInterface, id string) (*Author, error)
	GetAuthors(session SessionInterface, id string) (*[]Author, error)
	GetBook(session SessionInterface, id string) (*Book, error)
	GetBooks(session SessionInterface, id string) (*[]Book, error)
}
